runtime: nodejs
env: flex
skip_files:
  - ^(.*/)?\node_modules$
  - ^(.*/)?\src$
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
